# Generated by Django 5.0.6 on 2024-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('weather_info', models.TextField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
